# Generated by Django 5.1.2 on 2024-11-05 16:58

import container.validator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=40)),
                ('dockerfile', models.TextField(blank=True, help_text='Define the Dockerfile content, use {{var}} for automatic replacement for key defined in options.', validators=[container.validator.validate_dockerfile])),
                ('target_tag', models.CharField(default='builder-{{image}}-{{tag}}', max_length=50)),
                ('default_options', models.JSONField(blank=True, default=dict, null=True)),
                ('options_are_mandatory', models.BooleanField(default=False, help_text='Define if {{var}} defined in are mandatory in build request, otherwise fallback to default options that must be defined.')),
            ],
        ),
        migrations.CreateModel(
            name='BuiltContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hash', models.CharField(blank=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variables', models.JSONField(blank=True, null=True)),
                ('logs', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, choices=[('queued', 'Queued'), ('success', 'Success'), ('failed', 'Failed'), ('running', 'Running'), ('warning', 'Warning')])),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.container')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('default_value', models.CharField(max_length=50)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.container')),
            ],
        ),
    ]
