# Generated by Django 5.1.2 on 2024-10-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('dockerfile', models.TextField(null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('FAILED', 'Failed'), ('SUCCESS', 'Success')], default='QUEUED', max_length=40)),
            ],
        ),
    ]
