# Generated by Django 5.1.2 on 2024-10-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='status',
        ),
    ]
