# Generated by Django 5.1.2 on 2024-11-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='builtcontainer',
            name='variables',
        ),
        migrations.AddField(
            model_name='builtcontainer',
            name='options',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
