# Generated by Django 5.1.2 on 2024-11-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0002_remove_builtcontainer_variables_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builtcontainer',
            name='options',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
