# Generated by Django 5.2.4 on 2026-03-30 10:25

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0003_alter_builtcontainer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.CharField(help_text='Define the Dockerfile content, use {{var}} for automatic replacement for key defined in options.', max_length=40, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_{}]+\\Z'), 'Enter a valid "slug" consisting of letters, numbers, underscores, hyphens, or curly braces.', 'invalid')]),
        ),
    ]
