# Generated by Django 5.1.2 on 2024-10-27 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0003_variables'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variables',
            new_name='Variable',
        ),
    ]
