# Generated by Django 5.1.2 on 2024-10-27 23:32

import container.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0004_rename_variables_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='dockerfile',
            field=models.TextField(null=True, validators=[container.validator.validate_dockerfile]),
        ),
    ]
