# Generated by Django 5.1.2 on 2024-10-28 08:22

import container.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0005_alter_container_dockerfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuiltContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, unique=True)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('variables', models.JSONField()),
                ('logs', models.TextField(blank=True)),
                ('status', models.TextField(blank=True, choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')])),
            ],
        ),
        migrations.AlterField(
            model_name='container',
            name='dockerfile',
            field=models.TextField(blank=True, default=None, validators=[container.validator.validate_dockerfile]),
            preserve_default=False,
        ),
    ]
