# Generated by Django 5.1.2 on 2024-10-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0006_builtcontainer_alter_container_dockerfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='builtcontainer',
            old_name='tag_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='builtcontainer',
            name='hash',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
