# Generated by Django 5.1.2 on 2024-10-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0007_rename_tag_name_builtcontainer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builtcontainer',
            name='hash',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='builtcontainer',
            name='variables',
            field=models.JSONField(blank=True),
        ),
    ]
