# Generated by Django 5.1.2 on 2024-10-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0008_alter_builtcontainer_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builtcontainer',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builtcontainer',
            name='variables',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
