# Generated by Django 5.1.2 on 2024-10-28 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0009_alter_builtcontainer_logs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='builtcontainer',
            name='container',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='container.container'),
            preserve_default=False,
        ),
    ]
