# Generated by Django 5.1.2 on 2024-10-28 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0010_builtcontainer_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='builtcontainer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='builtcontainer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
