# Generated by Django 5.1.2 on 2024-10-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0011_builtcontainer_created_at_builtcontainer_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='target_tag',
            field=models.CharField(default='builder-{{image}}-{{tag}}', max_length=50),
        ),
    ]
