# Generated by Django 5.1.2 on 2024-10-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0012_container_target_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.SlugField(max_length=40),
        ),
    ]
