# Generated by Django 5.1.2 on 2024-11-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0013_alter_container_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='builtcontainer',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='builtcontainer',
            name='status',
            field=models.TextField(blank=True, choices=[('queued', 'Queued'), ('success', 'Success'), ('failed', 'Failed'), ('running', 'Running'), ('warning', 'Warning')]),
        ),
    ]
