# Generated by Django 5.1.2 on 2024-11-04 09:51

import container.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0014_alter_builtcontainer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='default_options',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='container',
            name='dockerfile',
            field=models.TextField(blank=True, help_text='Define the Dockerfile content, use {{var}} for automatic replacement for key defined in options.', validators=[container.validator.validate_dockerfile]),
        ),
    ]
