# Generated by Django 5.1.2 on 2024-11-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0015_container_default_options_alter_container_dockerfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='default_options',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
