# Generated by Django 5.1.2 on 2024-11-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0016_alter_container_default_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='default_options',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
