# Generated by Django 5.1.2 on 2024-11-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0019_alter_container_default_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='options_are_mandatory',
            field=models.BooleanField(default=False, help_text='Define if {{var}} defined in are mandatory in build request, otherwise fallback to default options that must be defined.'),
        ),
    ]
