import re
from django.db import models
from . import validator
from django.forms import ValidationError
from jinja2 import Environment, meta
from git import repo

# Create your models here.

class Method(models.Model):
    name = models.CharField(max_length=40)
    description = models.CharField(max_length=100, null=True, blank=True)
    container = models.ForeignKey('container.Container', on_delete=models.CASCADE)
    script = models.TextField(help_text="Define the Dockerfile content, use {{var}} for automatic replacement for key defined in options. {{name}} can be used for the project name, {{url}} and {{branch}} are replaced by git respective info")
    stop_on_failure = models.BooleanField(default=True)
    secrets = models.ManyToManyField('secret.Secret', blank=True, help_text="Secrets will be exposed as environement variable with same name")

    def __str__(self):
        return self.name

    @property
    def options(self):
        env = Environment()
        parsed_content = env.parse(self.script)
        undeclared_variables = meta.find_undeclared_variables(parsed_content)
        for var in ['name', 'url', 'branch', 'version']:
            if var in undeclared_variables:
                undeclared_variables.remove(var)
        return [k for k in undeclared_variables] + self.container.options

    @property
    def serialized_secrets(self):
        return {x.name: x.secret for x in self.secrets.all()}

class Task(models.Model):
    flow = models.ForeignKey('Flow', on_delete=models.CASCADE)
    method = models.ForeignKey('Method', on_delete=models.CASCADE)
    priority = models.IntegerField()

    class Meta:
        unique_together = ['flow', 'priority']

class Flow(models.Model):
    name = models.CharField(max_length=40)
    description = models.CharField(max_length=100, null=True, blank=True)
    version_file = models.CharField(max_length=100, null=True, blank=True)
    version_regex = models.CharField(max_length=150, null=True, blank=True, help_text="Define regex with one capturing group.", validators=[validator.validate_regex_pattern])
    version_mandatory = models.BooleanField(default=True, help_text="Define if build failes if version is not found")

    @property
    def options(self):
        options = []
        for task in self.task_set.all():
            options += task.method.options
        for var in ['name', 'url', 'branch', 'version']:
            if var in options:
                options.remove(var)
        return options

    def get_version_content(self, version_content):
        '''Get version from string content'''
        pattern = re.compile(self.version_regex)
        m = re.search(pattern, version_content)
        if not m:
            raise ValueError("Regex didn't matched anything")
        return m.group(1)

    def get_version(self, version_file):
        '''Get version from file'''
        with open(version_file, 'r') as f:
            content = f.read()
            pattern = re.compile(self.version_regex)
            m = re.search(pattern, content)
            if not m:
                raise ValueError("Regex didn't matched anything")
            return m.group(1)


    def increment_version(self, tag: str) -> str:
        """
        Increments the last number in the version part (before the first dash) 
        by the number after the dash. Supports formats like:
        - '1.0.9-371-gxxxxxxx' → '1.0.380'
        - '1-371-gxxxxxxx' → '380'
        """
        match = re.match(r'^([\d.]+)-(\d+)-g[0-9a-f]+$', tag)
        if not match:
            raise ValueError("Tag is not in a valid format: VERSION-NUM-gHASH")

        version_part, commit_count = match.groups()
        parts = version_part.split('.')

        if not parts[-1].isdigit():
            raise ValueError("The last segment of the version must be a number")

        # Increment the last version number by the commit count
        parts[-1] = str(int(parts[-1]) + int(commit_count))

        # If it's a simple version (e.g., '1'), return just the incremented number
        new_version = '.'.join(parts) if len(parts) > 1 else parts[-1]
        return new_version


    def is_git_describe_version(version: str) -> bool:
        """
        Returns True if the version matches the format generated by `git describe`,
        like: '1.0.9-371-gabcdef0' or '1-2-g123abcd'
        """
        pattern = r'^[\d.]+-\d+-g[0-9a-f]+$'
        return bool(re.match(pattern, version))

    def gen_version(self, version_file):
        '''Gen version using git describe --tags'''
        new_version = repo.Repo("./").git.describe('--tags')
        clean_version = self.incr_git_version(new_version)
        return self.replace_version(version_file, clean_version)

    def replace_version(self, version_file, new_version):
        with open(version_file, 'r') as f:
            content = f.read()

        pattern = re.compile(self.version_regex)

        def replace_group_1(match):
            return match.group(0).replace(match.group(1), new_version)
    
        updated_content = re.sub(pattern, replace_group_1, content, count=1)

        with open(version_file, 'w') as f:
            f.write(updated_content)
        
        return self.get_version(version_file)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['pk']

    def clean(self):
        super().clean()
        if self.version_mandatory:
            if not self.version_file or not self.version_regex:
                raise ValidationError(
                    "When version is mandatory, you must define Version file and Version Regex", code="invalid")