# Generated by Django 5.1.2 on 2025-07-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixinfo',
            name='room_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
