# Generated by Django 5.2.4 on 2025-09-22 08:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_matrixinfo_room_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMatrixProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_account', models.CharField(blank=True, help_text='Your Matrix ID in format @username:domain (e.g., @user:matrix.org)', max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='invalid_matrix_id', message='Matrix account must be in format @username:domain (e.g., @user:matrix.org)', regex='^@[a-zA-Z0-9._=-]+:[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')])),
                ('matrix_notifications_enabled', models.BooleanField(default=False, help_text='Enable Matrix notifications for build status updates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Matrix Profile',
                'verbose_name_plural': 'User Matrix Profiles',
            },
        ),
    ]
