# Generated by Django 5.1.2 on 2024-11-05 21:40

import django.db.models.deletion
import flow.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('container', '0001_initial'),
        ('secret', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('version_file', models.CharField(max_length=100)),
                ('version_regex', models.CharField(help_text='Define regex with one capturing group.', max_length=150, validators=[flow.validator.validate_regex_pattern])),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('script', models.TextField(help_text='Define the Dockerfile content, use {{var}} for automatic replacement for key defined in options. {{name}} can be used for the project name, {{url}} and {{branch}} are replaced by git respective info')),
                ('stop_on_failure', models.BooleanField(default=False)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.container')),
                ('secrets', models.ManyToManyField(blank=True, help_text='Secrets will be exposed as environement variable with same name', to='secret.secret')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.flow')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.method')),
            ],
            options={
                'unique_together': {('flow', 'priority')},
            },
        ),
    ]
