# Generated by Django 5.1.2 on 2024-11-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flow',
            options={'ordering': ['pk']},
        ),
    ]
