# Generated by Django 5.1.2 on 2024-10-27 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='method',
        ),
        migrations.AddField(
            model_name='method',
            name='flow',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flow.flow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='method',
            name='priority',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='method',
            unique_together={('flow', 'priority')},
        ),
    ]
