# Generated by Django 5.1.2 on 2024-10-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_remove_flow_method_method_flow_method_priority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flow',
            old_name='expected_file',
            new_name='version_file',
        ),
        migrations.AddField(
            model_name='flow',
            name='version_regex',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
