# Generated by Django 5.1.2 on 2024-11-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_alter_flow_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='version_mandatory',
            field=models.BooleanField(default=True, help_text='Define if build failes if version is not found'),
        ),
    ]
