# Generated by Django 5.1.2 on 2024-10-27 23:51

import flow.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_rename_expected_file_flow_version_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='stop_on_failure',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flow',
            name='version_regex',
            field=models.CharField(help_text='Define regex with one capturing group.', max_length=150, validators=[flow.validator.validate_regex_pattern]),
        ),
    ]
