# Generated by Django 5.1.2 on 2024-11-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_flow_version_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='stop_on_failure',
            field=models.BooleanField(default=True),
        ),
    ]
