# Generated by Django 5.1.2 on 2024-10-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_method_stop_on_failure_alter_flow_version_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='name',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
