# Generated by Django 5.1.2 on 2024-11-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_alter_flow_version_file_alter_flow_version_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
