# Generated by Django 5.1.2 on 2024-10-31 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_method_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='method',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='method',
            name='priority',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.flow')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.method')),
            ],
            options={
                'unique_together': {('build', 'priority')},
            },
        ),
    ]
