# Generated by Django 5.1.2 on 2024-10-31 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0006_alter_method_unique_together_remove_method_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='flow',
        ),
    ]
