# Generated by Django 5.2.4 on 2026-03-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0006_flow_description_alter_method_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='replace_all',
            field=models.BooleanField(default=False, help_text='Replace all occurrences of the version pattern instead of just the first one'),
        ),
    ]
