# Generated by Django 5.1.2 on 2024-10-31 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0007_remove_method_flow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='build',
            new_name='flow',
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('flow', 'priority')},
        ),
    ]
