# Generated by Django 5.2.4 on 2026-03-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0007_flow_replace_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='disable_notification',
            field=models.BooleanField(default=False, help_text='Disable Redmine and Matrix notifications for this flow'),
        ),
    ]
