# Generated by Django 5.1.2 on 2024-11-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0008_rename_build_task_flow_alter_task_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10, null=True),
        ),
    ]
