# Generated by Django 5.1.2 on 2024-11-01 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0009_task_logs_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='logs',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
