# Generated by Django 5.1.2 on 2024-11-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0010_remove_task_logs_remove_task_status'),
        ('secret', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='secrets',
            field=models.ManyToManyField(blank=True, help_text='Secrets will be exposed as environement variable with same name', to='secret.secret'),
        ),
    ]
