# Generated by Django 5.1.2 on 2024-11-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0011_method_secrets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='script',
            field=models.TextField(help_text='Define the Dockerfile content, use {{var}} for automatic replacement for key defined in options. {{name}} can be used for the project name, {{url}} and {{branch}} are replaced by git respective info'),
        ),
    ]
